name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend:
    name: Backend Build (KVR)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: KVR
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: KVR/package-lock.json

      - name: Install deps
        run: npm ci

      - name: Type check and build
        run: npm run build

  frontend:
    name: Frontend Build (Frontend)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: Frontend/package-lock.json

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build
